"use client";

import { Navbar } from "@/components/sections/navbar";
import { Footer } from "@/components/sections/footer";
import { motion } from "framer-motion";

export default function TermsPage() {
    return (
        <div className="min-h-screen bg-background text-foreground">
            <Navbar />

            <main className="relative px-4 pt-32 pb-16">
                {/* Background Effects */}
                <div className="absolute inset-0 bg-[linear-gradient(to_right,#ffffff08_1px,transparent_1px),linear-gradient(to_bottom,#ffffff08_1px,transparent_1px)] bg-[size:4rem_4rem] [mask-image:radial-gradient(ellipse_60%_50%_at_50%_0%,#000_70%,transparent_110%)] pointer-events-none" />

                <div className="relative z-10 mx-auto max-w-4xl">
                    <motion.div
                        initial={{ opacity: 0, y: 20 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ duration: 0.6 }}
                    >
                        <h1 className="text-4xl font-bold tracking-tight sm:text-5xl mb-4">
                            67Lab.ai – Terms of Service
                        </h1>
                        <p className="text-xl text-muted-foreground mb-8">
                            Version: 2.0 (Deploy-Ready)
                        </p>
                        <div className="prose prose-invert max-w-none">
                            <p className="text-lg mb-8">
                                Effective Date: February 2, 2026
                            </p>

                            <p className="mb-8">
                                Welcome to the Lab. These Terms of Service ("Terms") govern your access to and use of the website, services, and software provided by 67Lab.ai ("67Lab", "we", "us", or "our"). By accessing our "Lab" or using our services, you agree to be bound by these Terms. If you do not agree, you are not authorized to use the services.
                            </p>

                            <section className="mb-10">
                                <h2 className="text-2xl font-bold mb-4 text-primary">1. The "67" Dictionary: Definitions</h2>
                                <ul className="space-y-4 list-disc pl-5">
                                    <li>
                                        <strong>"Services":</strong> Refers to the AI integration, process automation, financial modeling, and software development provided via 67Lab.ai.
                                    </li>
                                    <li>
                                        <strong>"The Lab":</strong> Our interactive development environment, staging areas, and experimental AI features.
                                    </li>
                                    <li>
                                        <strong>"Output":</strong> The results, data, code, or content generated by our AI systems based on your Input.
                                    </li>
                                    <li>
                                        <strong>"Input":</strong> Any data, text, or files provided by the User to the Services.
                                    </li>
                                    <li>
                                        <strong>"The Stack":</strong> The underlying proprietary frameworks (Next.js, Python, LangGraph) used by 67Lab to deliver Services.
                                    </li>
                                </ul>
                            </section>

                            <section className="mb-10">
                                <h2 className="text-2xl font-bold mb-4 text-primary">2. Services & License Grant</h2>
                                <p className="mb-4">
                                    67Lab grants you a non-exclusive, non-transferable, revocable license to access our Services. We are not selling you our "engine"; we are granting you a license to use the results produced by that engine.
                                </p>
                                <p className="mb-4">
                                    <strong>Evolution of Services:</strong> We are "always in the lab." We reserve the right to modify, upgrade, or deprecate features without prior notice to ensure the highest technical standards.
                                </p>
                                <p>
                                    <strong>Alpha/Beta Features:</strong> Experimental features marked as "Lab Only" are provided "As-Is" and may contain bugs. Use at your own risk.
                                </p>
                            </section>

                            <section className="mb-10">
                                <h2 className="text-2xl font-bold mb-4 text-primary">3. User Obligations & "Rules of the Lab"</h2>
                                <p className="mb-4">To maintain the integrity of our high-concurrency systems, you agree NOT to:</p>
                                <ul className="space-y-4 list-disc pl-5">
                                    <li>
                                        <strong>Reverse Engineer:</strong> You shall not attempt to extract the source code or the specific "prompt weights" of our proprietary AI agents.
                                    </li>
                                    <li>
                                        <strong>Abuse API Limits:</strong> Rate-limiting is strictly enforced. Attempting to bypass these limits will result in an immediate "Lab Lockout."
                                    </li>
                                    <li>
                                        <strong>Illegal Use:</strong> You may not use 67Lab to generate malware, facilitate financial fraud, or violate any global data privacy laws.
                                    </li>
                                    <li>
                                        <strong>Human-in-the-Loop:</strong> You acknowledge that for high-stakes financial or medical decisions, a human must review all AI Output before implementation.
                                    </li>
                                </ul>
                            </section>

                            <section className="mb-10">
                                <h2 className="text-2xl font-bold mb-4 text-primary">4. AI Technology & Content Rights</h2>
                                <p className="mb-4">In 2026, the boundary between "User-owned" and "AI-generated" is critical.</p>
                                <ul className="space-y-4 list-disc pl-5">
                                    <li>
                                        <strong>Ownership of Input:</strong> You retain all rights to your Input.
                                    </li>
                                    <li>
                                        <strong>Ownership of Output:</strong> 67Lab hereby assigns to you all its right, title, and interest in and to the Output produced for your specific account, provided all fees are paid in full.
                                    </li>
                                    <li>
                                        <strong>Similarity of Content:</strong> You acknowledge that due to the nature of machine learning, Outputs may be similar across different users. We do not guarantee that your Output is unique.
                                    </li>
                                </ul>
                            </section>

                            <section className="mb-10">
                                <h2 className="text-2xl font-bold mb-4 text-primary">5. Third-Party Model Providers</h2>
                                <p className="mb-4">67Lab is an orchestration layer. Our Services rely on third-party Large Language Models (LLMs) including but not limited to OpenAI, Anthropic, and Google Gemini.</p>
                                <ul className="space-y-4 list-disc pl-5">
                                    <li>
                                        <strong>Pass-Through Terms:</strong> You agree to abide by the Acceptable Use Policies of these third-party providers.
                                    </li>
                                    <li>
                                        <strong>Service Reliance:</strong> If an upstream provider (e.g., Google Cloud) experiences an outage, 67Lab is not liable for service interruptions.
                                    </li>
                                </ul>
                            </section>

                            <section className="mb-10">
                                <h2 className="text-2xl font-bold mb-4 text-primary">6. Financial Terms & Precision Billing</h2>
                                <ul className="space-y-4 list-disc pl-5">
                                    <li>
                                        <strong>Fees:</strong> Services are billed according to the agreed-upon Statement of Work (SOW) or subscription tier.
                                    </li>
                                    <li>
                                        <strong>Taxes:</strong> You are responsible for all applicable sales, use, or value-added taxes.
                                    </li>
                                    <li>
                                        <strong>Late Payments:</strong> Because we operate with financial precision, late payments (30+ days) will result in a suspension of AI API access.
                                    </li>
                                </ul>
                            </section>

                            <section className="mb-10">
                                <h2 className="text-2xl font-bold mb-4 text-primary">7. Data Sovereignty & Confidentiality</h2>
                                <ul className="space-y-4 list-disc pl-5">
                                    <li>
                                        <strong>Confidential Information:</strong> "67" means business. We treat your proprietary data as a trade secret. We will not disclose your Input to third parties except as required to provide the Services (e.g., sending data to an LLM provider via encrypted API).
                                    </li>
                                    <li>
                                        <strong>Data Deletion:</strong> Upon termination, you may request the "Lab Wipe" protocol to ensure all your data is purged from our active processing layers.
                                    </li>
                                </ul>
                            </section>

                            <section className="mb-10">
                                <h2 className="text-2xl font-bold mb-4 text-primary">8. Limitation of Liability (The "Risk Management" Clause)</h2>
                                <p className="mb-4 italic">This is our most critical section. Read it carefully.</p>
                                <ul className="space-y-4 list-disc pl-5">
                                    <li>
                                        <strong>No Consequential Damages:</strong> To the maximum extent permitted by law, 67Lab shall not be liable for any indirect, incidental, or punitive damages, including loss of profits or data.
                                    </li>
                                    <li>
                                        <strong>The "Hallucination" Disclaimer:</strong> You acknowledge that AI can "hallucinate" or produce inaccurate information. 67Lab is not liable for financial losses incurred due to unverified AI Output.
                                    </li>
                                    <li>
                                        <strong>Liability Cap:</strong> 67Lab’s total aggregate liability for any claim shall not exceed the amount you paid to 67Lab in the six (6) months preceding the claim.
                                    </li>
                                </ul>
                            </section>

                            <section className="mb-10">
                                <h2 className="text-2xl font-bold mb-4 text-primary">9. Warranties & Disclaimers</h2>
                                <ul className="space-y-4 list-disc pl-5">
                                    <li>
                                        <strong>"As-Is":</strong> Our Services are provided "AS IS" and "AS AVAILABLE." We disclaim all warranties, express or implied, including warranties of merchantability or fitness for a particular purpose.
                                    </li>
                                    <li>
                                        <strong>No Financial Advice:</strong> 67Lab provides technical infrastructure. We are NOT financial advisors. Any financial modeling output should be verified by a certified professional.
                                    </li>
                                </ul>
                            </section>

                            <section className="mb-10">
                                <h2 className="text-2xl font-bold mb-4 text-primary">10. Termination</h2>
                                <ul className="space-y-4 list-disc pl-5">
                                    <li>
                                        <strong>By You:</strong> You can leave the Lab at any time by closing your account.
                                    </li>
                                    <li>
                                        <strong>By Us:</strong> We may terminate your access for a breach of these Terms, including non-payment or "toxic" use of our AI models.
                                    </li>
                                </ul>
                            </section>

                            <section className="mb-10">
                                <h2 className="text-2xl font-bold mb-4 text-primary">11. Dispute Resolution & Governing Law</h2>
                                <ul className="space-y-4 list-disc pl-5">
                                    <li>
                                        <strong>Arbitration First:</strong> Any dispute arising from these Terms will be resolved through binding arbitration, rather than in court.
                                    </li>
                                    <li>
                                        <strong>Governing Law:</strong> These Terms are governed by the laws of the jurisdiction where 67Lab is registered, without regard to conflict of law principles.
                                    </li>
                                </ul>
                            </section>

                            <section className="mb-10">
                                <h2 className="text-2xl font-bold mb-4 text-primary">12. Contact The Lab</h2>
                                <p className="mb-2">For legal inquiries or formal notices:</p>
                                <p className="mb-1"><strong>Email:</strong> <a href="mailto:ops@67lab.ai" className="text-primary hover:underline">ops@67lab.ai</a></p>
                                <p><strong>Attention:</strong> Legal Operations / Compliance Dept.</p>
                            </section>
                        </div>
                    </motion.div>
                </div>
            </main>

            <Footer />
        </div>
    );
}
